services:
  awesome-build:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    image: awesome:build
  awesome-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tsuroo/awesome-web:${CURRENT_GIT_REF:-main}