name: module3_task3
on:
  push:
    tags:
      - 1.0.*
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup
        run: |
          cd module3_task3
          ./setup.sh
      - name: Lint
        run: |
          cd module3_task3
          make lint
      - name: Build
        run: |
          cd module3_task3
          make build
      - name: Unit Tests
        run: |
          cd module3_task3
          make unit-tests
      - name: Integration Tests
        run: |
          cd module3_task3
          make integration-tests
      - name: Validate
        run: |
          cd module3_task3
          make validate
      - name: Package
        uses: actions/upload-artifact@v3
        with:
          name: awesomeWebsiteZip
          path: module3_task3/awesome-website.zip
        with:
          name: deployMd
          path: module3_task3/DEPLOY.md
        run: |
          cd module3_task3
          make package
  Release:
    needs: Build
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/1.0.')
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        uses: actions/download-artifact@v3
        with:
          name: awesomeWebsiteZip
