name: release_drafter
on:
  push:
    tags:
      - 1.0.*
  pull_request:
    types:
      - closed

name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  ## Changes

  $CHANGES

jobs:
  Merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: release-drafter/release-drafter@v5
