name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  Task-0:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup
        run: |
          cd module3_task1
          ./setup.sh
      - name: Lint
        run: make lint
      - name: Build
        run: make build
      - name: Unit Tests
        run: make unit-tests
      - name: Integration Tests
        run: make integration-tests
      - name: Validate
        run: make validate
