name: release_drafter
on:
  push:
    tags:
      - 1.0.*
  pull_request:
    types:
      - closed

jobs:
  Merged:
    if: github.event.pull_request.merged == true && startsWith(github.ref, 'refs/tags/1.0.')
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
